# Generated by Django 5.0 on 2024-01-01 21:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_customuser_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
