# Generated by Django 5.0 on 2024-01-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_order_guest_remove_order_total_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
