# Generated by Django 5.0 on 2024-01-02 10:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_order_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='orders',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='author',
            field=models.CharField(choices=[('user', 'User'), ('guest', 'Guest')], default='user', max_length=50),
        ),
    ]
