# Generated by Django 5.0 on 2024-01-02 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
