# Generated by Django 5.0 on 2024-01-02 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0012_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='author',
        ),
        migrations.AddField(
            model_name='order',
            name='owner_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='owner_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
    ]
