# Generated by Django 5.0 on 2024-01-05 11:25

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_guest_id_alter_order_id_alter_orderitem_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shippingPrice',
            new_name='shipping_price',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='taxPrice',
            new_name='tax_price',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='totalPrice',
            new_name='total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='isWhatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guest',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False, unique=True),
        ),
    ]
