# Generated by Django 5.0 on 2024-02-19 16:39

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('body', models.TextField(max_length=2000)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('to', models.CharField(blank=True, choices=[('all', 'ALL'), ('admin', 'ADMIN'), ('customer', 'CUSTOMER')], max_length=8, null=True)),
                ('seen', models.BooleanField(blank=True, default=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('body', models.TextField(max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(max_length=2000)),
                ('price', models.DecimalField(decimal_places=1, max_digits=10)),
                ('category', models.CharField(choices=[('shirt', 'Shirt'), ('t-shirt', 'T-shirt'), ('pants', 'Pants')], max_length=10)),
                ('gender', models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('unisex', 'Unisex')], max_length=10)),
                ('tag', models.CharField(choices=[('featured', 'Featured'), ('new-arrival', 'New Arrival')], max_length=11, null=True)),
                ('vote', models.IntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('out_of_stock', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('main_image', models.ImageField(upload_to='')),
                ('sub_image_1', models.ImageField(upload_to='')),
                ('sub_image_2', models.ImageField(upload_to='')),
                ('sub_image_3', models.ImageField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='adminpanel.product')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('stock_XS', models.IntegerField(default=0)),
                ('stock_S', models.IntegerField(default=0)),
                ('stock_M', models.IntegerField(default=0)),
                ('stock_L', models.IntegerField(default=0)),
                ('stock_XL', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='adminpanel.product')),
            ],
        ),
    ]
